### PR TITLE
Add end to end tests

### PR DESCRIPTION
**Pull request by shrishrirang**
- There are many ways in which the Javascript SDK can be consumed:
  - SDK bundle in an HTML script tag
  - SDK bundle as commonjs module
  - SDK bundle as AMD module
  - npm package along with browserify
  - npm package along with webpack
- Each of them have unique issues and warrant and end to end testing setup 
- This PR adds a directory for each of the above scenarios (e2etest\app\browser-* directories)
- First few commits in this PR restructure the e2etest directory. More details are available in individual commits.
- All the e2etest\app\browser-* directories share test code. package.json and gruntfile.js contain changes to be able to share code.

### CODE REVIEW

**Comment by shrishrirang** [comment]
@danderson00

**Comment by danderson00** [comment]
From what I can gather, this PR just sets up the E2E tests to be run against each platform, i.e. there are no actual additional tests?

It looks like the HTML runner is duplicated for each platform? This is not ideal - if we need to change the HTML template, it needs to be updated in many places. Is there a better solution?

**Comment by shrishrirang** [comment]
The SDK can be consumed in multiple ways and there are nuances of each that warrant a dedicated e2e setup for each. These are the various scenarios we want to be able to test:
- SDK bundle in an HTML script tag
- SDK bundle as commonjs module
- SDK bundle as AMD module
- npm package along with browserify
- npm package along with webpack

There is one browser-* directory per scenario listed above.

The tests are shared across all, which is bulk of the code. `index.html` and build steps differ for each of the above - some will need build steps, some won't, etc and hence that part is duplicated **with subtle differences** on purpose. There is no benefit of sharing beyond this point plus it is difficult to do so.

**Comment by shrishrirang** [comment]
Btw - https://github.com/shrishrirang/azure-mobile-apps-js-client/tree/rel-e2e/e2etest/misc and https://github.com/shrishrirang/azure-mobile-apps-js-client/tree/rel-e2e/e2etest/tests is the shared code which is bulk of the test / test framework code

**Comment by danderson00** [comment]
Do we really need to support all of the above scenarios?

**Comment by shrishrirang** [comment]
Which one do you want to unsupport ;)

**Comment by danderson00** [comment]
If they provide genuine value to our customers, we should keep them, but if we're doing it because we can, we shouldn't. Consider also the overhead of automating these.

**Pull request merged**
