### PR TITLE
Pull should stop only when the result size is 0

### PR DESCRIPTION
**Pull request by shrishrirang**
- Fixed an incorrect termination condition (`isPullComplete()`).
- Fixed a bug in how date objects were being compared. We need to convert the date objects to seconds since epoch and then compare them.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@shrishrirang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by shrishrirang** [comment]
@danderson00

**Comment by shrishrirang** [comment]
Closes https://github.com/Azure/azure-mobile-apps-js-client/issues/132

**Comment by danderson00** [comment]
Looks good

**Pull request merged**
